// table.names.ts
const t = {
    ADDON_CONTACT_US: 'addon_contact_us',
    ADDON_SUBJECTS: 'addon_subjects',
    ADDON_VISITORS_BOOK: 'addon_visitors_book',
    AFFILIATE_ACCOUNTS: 'affiliate_accounts',
    AFFILIATE_NOTIFICATIONS: 'affiliate_notifications',
    AFFILIATE_WITHDRAWALS: 'affiliate_withdrawals',
    BLOG_FEEDS: 'blog_feeds',
    BLOG_COMMENTS: 'blog_comments',
    BLOG_SETTINGS: 'blog_settings',
    O34MS_MANAGERS: 'o34ms_managers',
    SCH_CBT_ANSWERS: '_cbt_answers',
    SCH_CBT_LISTS: '_cbt_lists',
    SCH_CBT_QUESTIONS: '_cbt_questions',
    SCH_CHATS: '_chats',
    SCH_CHAT_GROUPS: '_chat_groups',
    SCH_CLASS_HISTORY: '_class_history',
    SCH_CLASS_INFO: '_class_info',
    SCH_CLASS: '_class_',
    SCH_FEE: '_fees',
    SCH_GALLERY: '_gallery',
    SCH_GROUP: '_groups',
    SCH_LOGS: '_logs',
    SCH_LOGIN: '_logins',
    SCH_SETTINGS: '_settings',
    SCH_STAFF: '_staffs',
    SCH_GUARDIAN: '_guardians',
    SCH_STUDENTS: '_students',
    SCH_SUBJECTS: '_subjects',
    SYS_API: 'sys_apis',
    SYS_CARDS_NATIVE: 'sys_cards_native',
    SYS_ERROR: 'sys_errors',
    SYS_SCHOOLS: 'sys_schools',
    SYS_STATUSES: 'sys_statuses', 
}

export default t;